apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-service
  namespace: default
  labels:
    app: dns-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-service
  template:
    metadata:
      labels:
        app: dns-service
    spec:
      containers:
        - name: dnsd
          image: dnsd:latest
          imagePullPolicy: Never
          args:
            - "-port"
            - "53"
            - "-http-port"
            - "8081"
            - "-zone-file"
            - "/data/records.json"
          ports:
            - name: dns-udp
              containerPort: 53
              hostPort: 53
              protocol: UDP
            - name: http-api
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: dns-storage
              mountPath: /data
      volumes:
        - name: dns-storage
          hostPath:
            path: /home/opc/dns-data
            type: DirectoryOrCreate
