apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-data-pvc
  namespace: default
  labels:
    app: dns-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
