apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-service-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-ingress-watcher
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-ingress-watcher-binding
subjects:
  - kind: ServiceAccount
    name: dns-service-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dns-ingress-watcher
  apiGroup: rbac.authorization.k8s.io
