apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: default
  labels:
    app: dns-service
spec:
  type: NodePort
  selector:
    app: dns-service
  ports:
    - name: http-api
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
