apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: dns-service
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: http-api
      port: 8081
      targetPort: 8081
      protocol: TCP
